### PR TITLE
handle whitespace for file uploads (attempt 2)

### LINKED ISSUE #427: CSV file upload breaks if whitespace in filename
Steps to reproduce

Upload any CSV contain `WORD \s WORD.csv` to Octopub publication. Upload should hang

Logs should show:

`Completed 500 Internal Server Error in 45ms (ActiveRecord: 5.1ms) (etc.)`
```URI::InvalidURIError (bad URI(is not URI?): https://octopub-dev.s3-eu-west-1.amazonaws.com/uploads/eac6e230-05db-47ed-9454-c2c143b83c98/WORD WORD.csv):```

### PR DESCRIPTION
**Pull request by Floppy**
Fixes #427. We upload to s3 and then download, both using the s3 API not public URLs. But we were turning the storage keys into URLs for passing around, completely unnecessarily. This change makes the code just pass around storage keys, which don't need special encoding.

### CODE REVIEW

**Comment by Floppy** [comment]
I think this now has the real fix. We upload to s3 and then download, both using the s3 API not public URLs. But we were turning the storage keys into URLs for passing around, completely unnecessarily. This change makes the code just pass around storage keys, which don't need special encoding.

**Comment by quadrophobiac** [comment]
Hey @Floppy is this good to review or is it still WIP?

File: spec/controllers/datasets/update_spec.rb [hunk 1]
```diff
@@ -305,7 +305,7 @@
         {
           title: "New file",
           description: "New file description",
-          file: "http://example.com/new-file.csv",
```
Comment (quadrophobiac) [inline spec/controllers/datasets/update_spec.rb]: how come example.com is removed in this spec?

**Comment by Floppy** [comment]
Good to go.

File: spec/controllers/datasets/update_spec.rb (hunk 1 above)
Comment (Floppy) [inline spec/controllers/datasets/update_spec.rb]: Because the file key in the S3 uploader is no longer a URL, just the storage key. So I've removed the protocol and port which would have been added before.

**Comment by Floppy** [comment]
Sorry forgot to remove WIP tag, this is OK to merge.
